# Introduction {#introduction}

Nutrition and food security surveys provide the information from which to assess the nutritional and food security status of a population. This document provides guidance on specific aspects of conducting nutrition and food security surveys. Chapter 2 to 7 focus on the various anthropometric measurements performed during nutrition surveys. [Chapter 2](#anthro) first describes two forms of undernutrition - acute undernutrition and chronic undernutrition - and then explains each including the signs and symptoms associated and the anthropometric indices used to diagnose them. [Chapter 3](#weight), \@ref(height), \@ref(muac), and \@ref(oedema) describes the equipment needed, the personnel required and the steps to undertake in performing weight, height, MUAC and oedema measurements respectively. [Chapter 7](#standard) then discusses how survey personnel can be assessed as to their abilities to perform the various anthropometric measurements through a standardisation test.

[Chapter 8](#diet) and \@ref(food) then talks about dietary diversity and food consumption, two indicator sets that are used for food security assessments. In [Chapter 8](#diet), minimum dietary diversity for women (MDD-W) and minimum dietary diversity for children under 2 years (MDD) are discussed particulary the standard questoinnaire used and the different food groups assessed. In [Chapter 9](#food), the food consumption score (FCS) is described including the standard questionnaire used and the different food groups assessed. Finally, [Chapter 9](#hfias) talks about the Household Food Insecurity Access Scale (HFIAS), the standard questions used to develop a questionnaire and the three food security domains it assesses.

Througout this document, there are boxed texts (specific blocks of text) that are meant to provide either a note/information, a reminder, a warning related to the topic being discusssed. In addition, there are boxed texts that point to downloadable forms or documents that the main body of text is referring to.