# Measuring dietary diversity {#sec-diet-diversity}

## Introduction
Dietary diversity can be measured in various ways with the traditional approach being time consuming, expensive, and requiring a high level of technical skill both in data collection and analysis. Recent development work in this indicator has brought about the use of a qualitative approach to food consumption that reflects household access to a wide variety of foods, and is also a proxy of the nutrient adequacy of the diet for individuals. The approach uses a specifically designed and tested dietary diversity questionnaire as a tool to elicit food consumption information in a more rapid, user-friendly and cost-effective approach. Administration of the questionnaire is straightforward and can be handled easily by trained enumerators. The scoring and/or analysis of the information gained from the questionnaire is easy to understand, quick to implement, and can be applied with minimal technical expertise.

In general, dietary diversity indicators are created by summing either the number of individual foods or food groups consumed over a reference period. This [chapter](#diet) describes how an individual dietary diversity indicator is created through a simple count of food groups that an individual has consumed over the past 24 hours. Specifically, this [chapter](#diet) discusses how the minimum dietary diversity indicator for women (MDD-W) and the minimum dietary diversity indicator for children under 2 years old (MDD) are calculated using a standard dietary diversity questionnaire.

## Minimum dietary diversity for women (MDD-W)

MDD-W is a dichotomous indicator of whether or not women 15–49 years of age have consumed at least five out of ten defined food groups the previous day or night. The proportion of women 15–49 years of age who reach this minimum in a population can be used as a proxy indicator for higher micronutrient adequacy, one important dimension of diet quality.

The indicator is calculated as follows:

$$ \text{MDD-W} = \frac{\text{Women 15-49 years of age who consumed 5 out of 10 food groups in the previous day or night}}{\text{Women 15-49 years of age}} $$

The ten food groups are:

1. Grains, white roots and tubers, and plantains
2. Pulses (beans, peas and lentils)
3. Nuts and seeds
4. Dairy
5. Meat, poultry and fish
6. Eggs
7. Dark green leafy vegetables
8. Other vitamin A-rich fruits and vegetables
9. Other vegetables
10. Other fruits

### MDD-W questionnaire

The following is a model questionnaire used for eliciting dietary diversity information from a women 15-49 years old.

**1. Following are required elements of the questionnaire**

+-----+-----------------------+----------------------------------------------------------------------+---------------+
|     | **Food categories**   | **Description and/or examples (to be adapted to local context)**     | **Consumed?** |
+:===:+=======================+======================================================================+===============+
| A   | Food made from grains | Porridge, bread, rice, pasta/noodles or other foods made from grains | Yes = 1       |  
|     |                       |                                                                      |  No = 2       |  
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| B   | White roots and tubers| White potatoes, white yams, manioc/cassava/yucca, coco yam, taro or  | Yes = 1       |  
|     |                       | any other foods made from white-fleshed roots or tubers, or plantains|  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| C   | Pulses (beans, peas   | Mature beans or peas (fresh or dried seed), lentils or bean/pea      | Yes = 1       |  
|     | and lentils)          | products, including hummus, tofu and tempeh                          |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| D   | Nuts and seeds        | Any tree nut, groundnut/peanut or certain seeds, or nut/seed         | Yes = 1       |  
|     |                       | “butters” or pastes                                                  |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| E   | Milk and milk products| Milk, cheese, yoghurt or other milk products but NOT including       | Yes = 1       |
|     |                       | butter, ice cream, cream or sour cream                               |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| F   | Organ meat            | Liver, kidney, heart or other organ meats or blood-based foods,      | Yes = 1       |
|     |                       | including from wild game                                             |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| G   | Meat and poultry      | Beef, pork, lamb, goat, rabbit, wild game meat, chicken, duck or     | Yes = 1       |
|     |                       | other bird                                                           |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| H   | Fish and seafood      | Fresh or dried fish, shellfish or seafood                            | Yes = 1       |
|     |                       |                                                                      |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| I   | Eggs                  | Eggs from poultry or any other bird                                  | Yes = 1       |
|     |                       |                                                                      |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| J   | Dark green leafy      | List examples of any medium-to-dark green leafy vegetables,          | Yes = 1       |
|     | vegetables            | including wild/foraged leaves                                        |  No = 2       |      
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| K   | Vitamin A-rich        | Pumpkin, carrots, squash or sweet potatoes that are yellow or orange | Yes = 1       |
|     | vegetables, roots and | inside                                                               |  No = 2       |     
|     | tubers                |                                                                      |               |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| L   | Vitamin A-rich fruits | Ripe mango, ripe papaya, some melons                                 | Yes = 1       |
|     |                       |                                                                      |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| M   | Other vegetables      | List examples of any other vegetables                                | Yes = 1       |
|     |                       |                                                                      |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| N   | Other fruits          | List examples of any other fruits                                    | Yes = 1       |
|     |                       |                                                                      |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+


**2. Optional components of the questionnaire**

+-----+-----------------------+----------------------------------------------------------------------+---------------+
|     | **Food categories**   | **Description and/or examples (to be adapted to local context)**     | **Consumed?** |
+:===:+=======================+======================================================================+===============+
| O   | Insects and other     | Insects, insect larvae/grubs, insect eggs and land and sea snails    | Yes = 1       |
|     | small protein foods   |                                                                      |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| P   | Red palm oil          | Red palm oil                                                         | Yes = 1       |
|     |                       |                                                                      |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| Q   | Other oils and fats   | Oil; fats or bu er added to food or used for cooking, including      | Yes = 1       |
|     |                       | extracted oils from nuts, fruits and seeds; and all animal fat       |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| R   | Savoury and fried     | Crisps and chips, fried dough or other fried snacks                  | Yes = 1       |
|     | snacks                |                                                                      |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| S   | Sweets                | Sugary foods, such as chocolates, candies, cookies/sweet biscuits    | Yes = 1       | 
|     |                       | and cakes, sweet pastries or ice cream                               |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| T   | Sugar-sweetened       | Sweetened fruit juices and “juice drinks”, soft drinks/fizzy drinks, | Yes = 1       |
|     | beverages             | chocolate drinks, malt drinks, yoghurt drinks or sweet tea or coffee |  No = 2       |
|     |                       | with sugar                                                           |               |
+-----+-----------------------+----------------------------------------------------------------------+---------------+


**3. Other required components of the questionniare but don't count in the food groups**

+-----+-----------------------+----------------------------------------------------------------------+---------------+
|     | **Food categories**   | **Description and/or examples (to be adapted to local context)**     | **Consumed?** |
+:===:+=======================+======================================================================+===============+
| U   | Condiments and        | Ingredients used in small quantities for flavour, such as chilies,   | Yes = 1       | 
|     | seasonings            | spices, herbs, powder, tomato paste, flavour cubes or seeds          |  No = 2       |
+-----+-----------------------+----------------------------------------------------------------------+---------------+
| V   | Other beverages and   | Tea or co ee if not sweetened, clear broth, alcohol                  | Yes = 1       |
|     | foods (optionally,    | Pickles, olives and similar                                          |  No = 2       |
|     | specify if not listed)|                                                                      |               |
+-----+-----------------------+----------------------------------------------------------------------+---------------+


### MDD-W food group description

**1. Grains, white roots and tubers, and plantains**

* Also called as "starchy staples""
* Examples include
    * breads and flatbreads
    * stiff porridges of maize, sorghum, millet or cassava (manioc)
    * pasta
    * potatoes
    * white-fleshed sweet potatoes
    * white yams
    * yucca
    * plantains (white-fleshed)
    
**2. Pulses (beans, peas and lentils)**

* Beans, peas and lentils the seeds of which are dried and used as food for processed into other food products
* Does not include the same plants eaten fresh in the pod or still green/immature (these are categorised as "other vegetables")
* Groundnut (peanut), a legume, is not included in this group (these are categorised as "nuts")
* Examples include
    * beans - black, kidney, pinto
    * broad bean - fava, field bean
    * chickpea (garbanzo)
    * pigeon pea
    * cowpea
    * lentil and soybean/soybean products or other legume products
    
**3. Nuts and seeds**

* Comprise mostly of tree nuts but also includes peanuts (groundnuts)
* Certain seeds consumed in substantial quantities (otherwise categorised as "condiments and seasonings")
* Includes nut and seed butters such as peanut butter, cashew butter or sesame butter (tahini)
* Examples of nuts are
    * cashew
    * macadamia
    * Brazil nut
    * almond
    * chestnut
    * hazelnut
    * pistachio
    * walnut
* Examples of seeds are
    * sesame
    * sunflower
    * pumpkin/squash/gourd
    * pine nut
    
**4. Dairy**

* Includes
    * Almost all liquid and solid dairy products from cows, goats, buffalo, sheep or camels. 
    * Tinned, powdered or ultra-high temperature (UHT) milk
    * Soft and hard cheeses
    * Yoghurt and kefir
* Excludes
    * Butter
    * Cream
    * Sour cream
    * Ice cream
    * Sweetened condensed milk
    * Processed/packaged “yoghurt drinks”

**5. Meat, poultry and fish**

* Sometimes referred to as "flesh foods"
* All meats, organ meats, poultry and other birds
* Fresh and dried fish and seafood/shellfish
* Wild birds and mammals (“bush meat”), 
* Snakes, frogs and other reptiles and amphibians

**6. Eggs**

* Includes eggs from any type of bird (domesticated poultry and wild birds)
* Excludes fish roe (categorised with small protein foods)

**7. Dark green leafy vegetables**

* All medium-to-dark green leafy vegetables 
* Only very light green leaves, such as iceberg lettuce, are not. 
* Medium green leaves, such as Chinese cabbage, romaine and bibb lettuce, along with darker greens are included
* Dark green leafy vegetables that are wild and foraged
* Dark green leafy vegetbles of other food crops such as cassava leaves, bean leaves, pumpkin leaves, amaranth leaves)

**8. Other vitamin A-rich fruits and vegetables**

* Vitamin A-rich fruits are
    * Ripe mango (not when eaten green; categorised as "other fruits")
    * Ripe papaya (not when eaten green; categorised as "other fruits")
    * Red palm fruit/pulp
    * Passion fruit
    * Apricot
    * Several types of melon
    * Ripe, deep yellow-fleshed or orange-fleshed bananas (distinguish from white-fleshed bananas)

* Vitamin A-rich vegetables
    * Orange-fleshed sweet potato (if white-fleshed, categorised as roots and tubers)
    * Carrot
    * Pumpkin
    * Deep yellow or orange-fleshed squash

**9. Other vegetables**

* Includes legumes when the fresh/green pod is consumed (as in fresh peas, snow peas, snap peas or green beans)
* Includes stems, fruits and  owers of plants when generally consumed in savoury dishes and considered as vegetables in culinary systems such as cucumber, tomato and okra
* Excludes white potatoes, white yams, cassava and coco yam

**10. Other fruits**

* Includes most fruits, excluding vitamin A-rich fruits
* Does not include tomatoes
* Plantains are classified with starchy staples but sweet white bananas are classified with fruit.


## Minimum dietary diversity (MDD) component of the infant and young child feeding (IYCF)

MDD component of the IYCF indicators is a dichotomous indicator of whether or not children 6-23 months of age receive foods from 4 or more food groups (out of a total of 7 food groups for children). The proportion of children 6–23 months of age who receive foods from 4 or more food groups is associated with better quality diets for both breastfed and non-breastfed children. Consumption of foods from at least 4 food groups on the previous day would mean that in most populations the child had a high likelihood of consuming at least one animal-source food and at least one fruit or vegetable that day, in addition to a staple food (grain, root or tuber).

The indicator is calculated as follows:

$$ \text{MDD} = \frac{\text{Children 6–23 months of age who received foods from} \geq \text{ 4 food groups during the previous day}}{\text{Children 6–23 months of age}} $$

The 7 foods groups used for tabulation of this indicator are:

1. Grains, roots and tubers
2. Legumes and nuts
3. Dairy products (milk, yoghurt, cheese)
4. Fresh foods (meat, fish, poultry and liver/organ meats)
5. Eggs
6. Vitamin-A rich fruits and vegetables
7. Other fruits and vegetables

Consumption of any amount of food from each food group is sufficient to “count”, i.e., there is no minimum quantity, except if an item is only used as a condiment.

### MDD questionnaire

Following is a model questionnaire used for MDD component of IYCF

+-----+-------------------------------------------------------------------------+------------------+
|     | **Questions and filters**                                               | **Response**     |
+:===:+=========================================================================+==================+
| A   | Porridge, bread, rice, noodles, or other foods made from grains         | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| B   | Pumpkin, carrots, squash, or sweet potatoes that are yellow or orange   | Yes = 1   No = 2 |
|     | inside                                                                  |                  |
+-----+-------------------------------------------------------------------------+------------------+
| C   | White potatoes, white yams, manioc, cassava, or any other foods made    | Yes = 1   No = 2 |
|     | from roots                                                              |                  |
+-----+-------------------------------------------------------------------------+------------------+
| D   | Any dark green leafy vegetables                                         | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| E   | Ripe mangoes, ripe papayas, or (insert other local vitamin A-rich       | Yes = 1   No = 2 |
|     | fruits)                                                                 |                  |
+-----+-------------------------------------------------------------------------+------------------+
| F   | Any other fruits or vegetables                                          | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| G   | Liver, kidney, heart, or other organ meats                              | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| H   | Any meat, such as beef, pork, lamb, goat, chicken, or duck              | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| I   | Eggs                                                                    | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| J   | Fresh or dried fish, shellfish, or seafood                              | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| K   | Any foods made from beans, peas, lentils, nuts, or seeds                | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| L   | Cheese, yoghurt, or other milk products                                  | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| M   | Any oil, fats, or butter, or foods made with any of these               | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| N   | Any sugary foods such as chocolates, sweets, candies, pastries, cakes,  | Yes = 1   No = 2 |
|     | or biscuits                                                             | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| O   | Condiments for flavour, such as chillies, spices, herbs, or fish powder | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| P   | Grubs, snails, or insects                                               | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+
| Q   | Foods made with red palm oil, red palm nut, or red palm nut pulp sauce  | Yes = 1   No = 2 |
+-----+-------------------------------------------------------------------------+------------------+


### MDD food group description

The food group description for MDD-W is about the same for the IYCF MDD with a few exceptions:

**1. Ice cream**

In MDD-W, ice cream is categorised as "sweets" because it is a high fat/high sugar food. For IYCF MDD, ice cream is categorised as dairy.

This difference is primarily due to increasing concerns with other dimensions of diet quality in the context of the nutrition transition given that ice cream is a high fat and high sugar food and also because many low-quality ice cream products contain very little dairy.

**2. Garlic**

In MDD-W, garlic is categorised as "condiments and seasonings" given that it is usually consumed in small quantities. In IYCF MDD, there is no particular concern for food quantity so garlic is categorised as "other fruits and vegetables".

**3. Olives**

In MDD-W, olives are categorised as "other foods and beverages" given that it is usually consumed in small quantities. In IYCF MDD, olives are categorised as "other fruits and vegetables".

**4. Red palm oil**

In MDD-W, this is totally excluded from the indicator calculation. In IYCF MDD, it is counted under "vitamin A-rich fruits and vegetables"

**5. Fish roe**

In MDD-W, categorised with "insects and other small protein foods". In IYCF MDD, categorised under "fish and seafood"

**6. Seaweed**

In MDD-W, categorised as "other vegetables". In IYCF MDD, categorised as "dark green leafy vegetables".

