# Measuring dietary diversity {#diet}

## Introduction
Dietary diversity can be measured in various ways with the traditional approach being time consuming, expensive, and requiring a high level of technical skill both in data collection and analysis. Recent development work in this indicator has brought about the use of a qualitative approach to food consumption that reflects household access to a wide variety of foods, and is also a proxy of the nutrient adequacy of the diet for individuals. The approach uses a specifically designed and tested dietary diversity questionnaire as a tool to elicit food consumption information in a more rapid, user-friendly and cost-effective approach. Administration of the questionnaire is straightforward and can be handled easily by trained enumerators. The scoring and analysis of the information gained from the questionnaire is easy to understand, quick to implement, and can be applied with minimal technical expertise.

In general, dietary diversity scores are created by summing either the number of individual foods or food groups consumed over a reference period. This [chapter](#diet) describes how an individual dietary diversity score is created through a simple count of food groups that an individual has consumed over the past 24 hours. Specifically, this [chapter](#diet) discusses how the dietary diversity score for women (MDD-W) and the dietary diversity score for children under 2 years old (MDD) are calculated using a standard dietary diversity questionnaire. This guide will not discuss household dietary diversity score.

## Minimum dietary diversity for women (MDD-W)

MDD-W is a dichotomous indicator of whether or not women 15–49 years of age have consumed at least five out of ten defined food groups the previous day or night. The proportion of women 15–49 years of age who reach this minimum in a population can be used as a proxy indicator for higher micronutrient adequacy, one important dimension of diet quality.

The ten food groups are:

1. Grains, white roots and tubers, and plantains
2. Pulses (beans, peas and lentils)
3. Nuts and seeds
4. Dairy
5. Meat, poultry and fish
6. Eggs
7. Dark green leafy vegetables
8. Other vitamin A-rich fruits and vegetables
9. Other vegetables
10. Other fruits

### MDD-W questionnaire


### MDD-W food group description

1. Grains, white roots and tubers, and plantains

* Also called as "starchy staples""
* Examples include
    * breads and flatbreads
    * stiff porridges of maize, sorghum, millet or cassava (manioc)
    * pasta
    * potatoes
    * white-fleshed sweet potatoes
    * white yams
    * yucca
    * plantains (white-fleshed)
    
2. Pulses (beans, peas and lentils)

* Beans, peas and lentils the seeds of which are dried and used as food for processed into other food products
* Does not include the same plants eaten fresh in the pod or still green/immature (these are categorised as "other vegetables")
* Groundnut (peanut), a legume, is not included in this group (these are categorised as "nuts")
* Examples include
    * beans - black, kidney, pinto
    * broad bean - fava, field bean
    * chickpea (garbanzo)
    * pigeon pea
    * cowpea
    * lentil and soybean/soybean products or other legume products
    
3. Nuts and seeds

* Comprise mostly of tree nuts but also includes peanuts (groundnuts)
* Certain seeds consumed in substantial quantities (otherwise categorised as "condiments and seasonings")
* Includes nut and seed butters such as peanut butter, cashew butter or sesame butter (tahini)
* Examples of nuts are
    * cashew
    * macadamia
    * Brazil nut
    * almond
    * chestnut
    * hazelnut
    * pistachio
    * walnut
* Examples of seeds are
    * sesame
    * sunflower
    * pumpkin/squash/gourd
    * pine nut
    
4. Dairy

* Includes
    * Almost all liquid and solid dairy products from cows, goats, buffalo, sheep or camels. 
    * Tinned, powdered or ultra-high temperature (UHT) milk
    * Soft and hard cheeses
    * Yoghurt and kefir
* Excludes
    * Butter
    * Cream
    * Sour cream
    * Ice cream
    * Sweetened condensed milk
    * Processed/packaged “yoghurt drinks”

5. Meat, poultry and fish

* Sometimes referred to as "flesh foods"
* All meats, organ meats, poultry and other birds
* Fresh and dried fish and seafood/shellfish
* Wild birds and mammals (“bush meat”), 
* Snakes, frogs and other reptiles and amphibians

6. Eggs

* Includes eggs from any type of bird (domesticated poultry and wild birds)
* Excludes fish roe (categorised with small protein foods)

7. Dark green leafy vegetables

* All medium-to-dark green leafy vegetables 
* Only very light green leaves, such as iceberg lettuce, are not. 
* Medium green leaves, such as Chinese cabbage, romaine and bibb lettuce, along with darker greens are included
* Dark green leafy vegetables that are wild and foraged
* Dark green leafy vegetbles of other food crops such as cassava leaves, bean leaves, pumpkin leaves, amaranth leaves)

8. Other vitamin A-rich fruits and vegetables

* Vitamin A-rich fruits are
    * Ripe mango (not when eaten green; categorised as "other fruits")
    * Ripe papaya (not when eaten green; categorised as "other fruits")
    * Red palm fruit/pulp
    * Passion fruit
    * Apricot
    * Several types of melon
    * Ripe, deep yellow-fleshed or orange-fleshed bananas (distinguish from white-fleshed bananas)

* Vitamin A-rich vegetables
    * Orange-fleshed sweet potato (if white-fleshed, categorised as roots and tubers)
    * Carrot
    * Pumpkin
    * Deep yellow or orange-fleshed squash

9. Other vegetables

* Includes legumes when the fresh/green pod is consumed (as in fresh peas, snow peas, snap peas or green beans)
* Includes stems, fruits and  owers of plants when generally consumed in savoury dishes and considered as vegetables in culinary systems such as cucumber, tomato and okra
* Excludes white potatoes, white yams, cassava and cocoyam

10. Other fruits

* Includes most fruits, excluding vitamin A-rich fruits
* Does not include tomatoes
* Plantains are classified with starchy staples but sweet white bananas are classified with fruit.


