# Measuring food consumption {#food}

## Introduction

The **Food Consumption Score (FCS)** is an index developed by the World Food Programme (WFP) in 1996. The **FCS** is a household level indicator that aggregates food group diversity and frequency over the past 7 days. These food groups are then weighted according to their relative nutritional value. This means that food groups that are nutritionally-dense such as animal products are given greater weight than those containing less nutritionally dense foods such as tubers. The weights are then added up to come up with a household score which are then used to classify households into either poor, borderline, or acceptable food consumption. The **FCS** is a measure of quantity of caloric intake.


## FCS questionnaire

A brief questionnaire is used to ask respondents about the frequency of their households’ consumption of eight different food groups over the previous seven days. The eight food groups are:

1. Main staples
2. Pulses
3. Vegetables
4. Fruit
5. Meat/fish
6. Milk
7. Sugar
8. Oil

Following is a model questionnaire that can be used for collecting data on **FCS**.


**Question:** I would like to ask you about all the different foods that your household members have eaten in the last 7 days. Could you please tell me how many days in the past week your household has eaten the following foods?

*(for each food, ask what the primary source of each food item eaten that week was, as well as the second main source of food, if any)*

+-----+----------------------------------------+--------------------+--------------------+--------------------+
|     | Food item                              | Number of days     | Primary source     | Secondary source   |
|     |                                        | eaten in the past  | (see codes)        | (see codes)        |
+:===:+========================================+====================+====================+====================+
| 1   | Maize                                  |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 2   | Rice                                   |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 3   | Bread/wheat                            |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 4   | Tubers                                 |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 5   | Groundnuts and pulses                  |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 6   | Fish (eaten as a main food)            |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 7   | Fish powder (used for flavor only)     |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 8   | Red meat (sheep/goat/beef)             |                    |                    |                    |  
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 9   | White meat (poultry)                   |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 10  | Vegetable oil, fats                    |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 11  | Eggs                                   |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 12  | Milk and dairy products (main food)    |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 13  | Milk in tea in small amounts           |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 14  | Vegetables (including leaves)          |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 15  | Fruits                                 |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+
| 16  | Sweets, sugar                          |                    |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+--------------------+

+-------------------------------------------------------------------------------------------------------------+
| **Food source codes:**                                                                                      |
+=============================================================================================================+
| Purchase = 1; Own production = 2; Traded goods/services, barter = 3; Borrowed = 4;                          |
| Received as gifts = 5; Food aid = 6; Others: (specify) = 7                                                  |
+-------------------------------------------------------------------------------------------------------------+

This model questionnaire should be adapted to each survey context in which it is to be used.

## Calculating the FCS

The **FCS** or the frequency weighted diet diversity score is a score calculated using the frequency of consumption of different food groups consumed by a household during the 7 days before the survey. Following are the steps to calculate the FCS:

**Step 1.** Using the standard questionnaire above, group all the food items into specific food groups (see groups in table below).

+-----+----------------------------------------+--------------------+--------------------+
|     | Food items                             | Food groups        | Weight             |
+:===:+========================================+====================+====================+
| 1   | Maize , maize porridge, rice, sorghum, | Main staples       | 2                  | 
|     | millet pasta, bread and other cereals  |                    |                    |
|     | Cassava, potatoes and sweet potatoes,  |                    |                    |
|     | other tubers, plantains                |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+
| 2   | Beans, peas, groundnuts and cashew nuts| Pulses             | 3                  |
+-----+----------------------------------------+--------------------+--------------------+
| 3   | Vegetables, leaves                     | Vegetables         | 1                  |
+-----+----------------------------------------+--------------------+--------------------+
| 4   | Fruits                                 | Fruits             | 1                  |
+-----+----------------------------------------+--------------------+--------------------+
| 5   | Beef, goat, poultry, pork, eggs and    | Meat and fish      | 4                  |
|     | fish                                   |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+
| 6   | Milk yogurt and other diary            | Milk               | 4                  |
+-----+----------------------------------------+--------------------+--------------------+
| 7   | Sugar and sugar products, honey        | Sugar              | 0.5                |
+-----+----------------------------------------+--------------------+--------------------+
| 8   | Oils, fats and butter                  | Oil                | 0.5                |
+-----+----------------------------------------+--------------------+--------------------+
| 9   | Spices, tea, coffee, salt, fishpower,  | Condiments         | 0                  |
|     | small amounts of milk for tea.         |                    |                    |
+-----+----------------------------------------+--------------------+--------------------+

**Step 2.** Sum all the consumption frequencies of food items of the same group, and recode the value of each group above 7 as 7.

**Step 3.** Multiply the value obtained for each food group by its weight (see food group weights in table below) and create new weighted food group scores.

**Step 4.** Sum the weighed food group scores, thus creating the food consumption score (FCS).

**Step 5.** Using the appropriate thresholds (see below), recode the variable food consumption score, from a continuous variable to a categorical variable.

+--------------------+----------------------------------------+
| **FCS**            | **Profiles**                           |
+====================+========================================+
| 0 - 21             | Poor                                   |
+--------------------+----------------------------------------+
| 21.5 - 35          | Borderline                             |
+--------------------+----------------------------------------+
| $>$ 35             | Acceptable                             |
+--------------------+----------------------------------------+
