# Household Food Insecurity Access Scale {#hfias}

## Introduction
Household Food Insecurity Access Scale (HFIAS) is one of the experience-based food insecurity scales. Experience-based indicators are constructed from a short questionnaire that captures households’ behavioural and psychological manifestations of insecure food access, such as having to reduce the number of meals consumed or cut back on the quality of the food due to a lack of resources. HFIAS was developed in 2006 by the USAID-funded Food and Nutrition Technical Assistance II project (FANTA) in collaboration with Tufts and Cornell Universities, among other partners.

## HFIAS questionnaire

The HFIAS uses a questionnaire of 9 items which are called **occurence questions** (i.e., whether condition stated in the question has happened or not) based on a 30-day recall. If condition has happened, a further question is then asked which is called a **frequency-of-occurence question**. The possible responses for the **frequency-of-occurence** are categorical - *rarely* (once or twice in the past four weeks); *sometimes* (three to ten times in the past four weeks); and *often* (more than ten times in the past four weeks).

The generic occurrence questions are as follows:

+-----+-----------------------------------------------------+------------------+
| Q1  | In the past four weeks, did you worry that your     | 0 = No; 1 = Yes  |
|     | household would not have enough                     |                  |
|     | food?                                               |                  |
+-----+-----------------------------------------------------+------------------+
| Q1a | How often did this happen?                          | 1 = Rarely       |
|     |                                                     |                  |
|     |                                                     | 2 = Sometimes    |
|     |                                                     |                  |
|     |                                                     | 3 = Often        |
+-----+-----------------------------------------------------+------------------+
| Q2  | In the past four weeks, were you or any household   | 0 = No; 1 = Yes  |
|     | member not able to eat the kinds of foods you       |                  |
|     | preferred because of a lack of resources?           |                  |
+-----+-----------------------------------------------------+------------------+
| Q2a | How often did this happen?                          | 1 = Rarely       |
|     |                                                     |                  |
|     |                                                     | 2 = Sometimes    |
|     |                                                     |                  |
|     |                                                     | 3 = Often        |
+-----+-----------------------------------------------------+------------------+
| Q3  | In the past four weeks, did you or any household    | 0 = No; 1 = Yes  |
|     | member have to eat a limited variety of foods due to|                  |
|     | a lack of resources?                                |                  |
+-----+-----------------------------------------------------+------------------+
| Q3a | How often did this happen?                          | 1 = Rarely       |
|     |                                                     |                  |
|     |                                                     | 2 = Sometimes    |
|     |                                                     |                  |
|     |                                                     | 3 = Often        |
+-----+-----------------------------------------------------+------------------+
| Q4  | In the past four weeks, did you or any household    | 0 = No; 1 = Yes  |
|     | member have to eat some foods that you really did   |                  |
|     | not want to eat because of a lack of resources to   |                  |
|     | obtain other types of food?                         |                  |
+-----+-----------------------------------------------------+------------------+
| Q4a | How often did this happen?                          | 1 = Rarely       |
|     |                                                     |                  |
|     |                                                     | 2 = Sometimes    |
|     |                                                     |                  |
|     |                                                     | 3 = Often        |
+-----+-----------------------------------------------------+------------------+
| Q5  | In the past four weeks, did you or any household    | 0 = No; 1 = Yes  |
|     | member have to eat a smaller meal than you felt you |                  |
|     | needed because there was not enough food?           |                  |
+-----+-----------------------------------------------------+------------------+
| Q5a | How often did this happen?                          | 1 = Rarely       |
|     |                                                     |                  |
|     |                                                     | 2 = Sometimes    |
|     |                                                     |                  |
|     |                                                     | 3 = Often        |
+-----+-----------------------------------------------------+------------------+
| Q6  | In the past four weeks, did you or any household    | 0 = No; 1 = Yes  |
|     | member have to eat fewer meals in a day because     |                  |
|     | there was not enough food?                          |                  |
+-----+-----------------------------------------------------+------------------+
| Q6a | How often did this happen?                          | 1 = Rarely       |
|     |                                                     |                  |
|     |                                                     | 2 = Sometimes    |
|     |                                                     |                  |
|     |                                                     | 3 = Often        |
+-----+-----------------------------------------------------+------------------+
| Q7  | In the past four weeks, was there ever no food to   | 0 = No; 1 = Yes  |
|     | eat of any kind in your household because of lack   |                  |
|     | of resources to get food?                           |                  |
+-----+-----------------------------------------------------+------------------+
| Q7a | How often did this happen?                          | 1 = Rarely       |
|     |                                                     |                  |
|     |                                                     | 2 = Sometimes    |
|     |                                                     |                  |
|     |                                                     | 3 = Often        |
+-----+-----------------------------------------------------+------------------+
| Q8  | In the past four weeks, did you or any household    | 0 = No; 1 = Yes  |
|     | member go to sleep at night hungry because there    |                  |
|     | was not enough food?                                |                  |
+-----+-----------------------------------------------------+------------------+
| Q8a | How often did this happen?                          | 1 = Rarely       |
|     |                                                     |                  |
|     |                                                     | 2 = Sometimes    |
|     |                                                     |                  |
|     |                                                     | 3 = Often        |
+-----+-----------------------------------------------------+------------------+
| Q9  | In the past four weeks, did you or any household    | 0 = No; 1 = Yes  |
|     | member go a whole day and night without eating      |                  |
|     | anything because there was not enough food?         |                  |
+-----+-----------------------------------------------------+------------------+
| Q9a | How often did this happen?                          | 1 = Rarely       |
|     |                                                     |                  |
|     |                                                     | 2 = Sometimes    |
|     |                                                     |                  |
|     |                                                     | 3 = Often        |
+-----+-----------------------------------------------------+------------------+

Questions 1 to 9 are the **occurence questions** while questions 1a to 9a are the **frequency-of-occurence questions**. 

## HFIAS indicators

Four types of indicators can be calculated to help understand the characteristics of and changes in household food insecurity in the surveyed population. These indicators are:

* Household Food Insecurity Access-related **Conditions** 

* Household Food Insecurity Access-related **Domains** 

* Household Food Insecurity Access Scale **Score** 

* Household Food Insecurity Access **Prevalence**


### Household Food Insecurity Access-related Conditions

This indicator set consists of the responses to the individual **occurence questions** and **frequency of occurence questions**. The indicators in this set provide specific, disaggregated information about the behaviours and perceptions of the surveyed households. The indicators present the percent of households that responded affirmatively to each question, regardless of the frequency of the experience. Thus they measure the percent of households experiencing the condition at any level of severity. Each indicator can be further disaggregated to examine the frequency of experience of the condition across the surveyed households.

1. Percent of households that worried about not having enough food in the past four weeks

$$ \frac{\text{Number of households with response = 1 to Q1}}{\text{Total number of households responding to Q1}} ~ \times ~ 100 $$

1a. Percent of households that **often** worried about not having enough food in the past four weeks

$$ \frac{\text{Number of households with response = 3 to Q1a}}{\text{Total number of households responding to Q1}} ~ \times ~ 100 $$ 

2. Percent of households with a household member/s not able to eat the kinds of food preferred because of a lack of resources

$$ \frac{\text{Number of households with response = 1 to Q2}}{\text{Total number of households responding to Q2}} ~ \times ~ 100 $$

2a. Percent of households with a household member/s who **often** are not able to eat the kinds of food preferred because of a lack of resources

$$ \frac{\text{Number of households with response = 3 to Q2a}}{\text{Total number of households responding to Q2}} ~ \times ~ 100 $$

3. Percent of households with a household member/s who have to eat a limited variety of foods due to a lack of resources

$$ \frac{\text{Number of households with response = 1 to Q3}}{\text{Total number of households responding to Q3}} ~ \times ~ 100 $$

3a. Percent of households with a household member/s who **often** have to eat limited variety of foods due to a lack of resources

$$ \frac{\text{Number of households with response = 3 to Q3a}}{\text{Total number of households responding to Q3}} ~ \times ~ 100 $$

4. Percent of households with a household member/s who have had to eat some foods they really didn't want to eat due to a lack of resources to obtain other types of food

$$ \frac{\text{Number of households with response = 1 to Q4}}{\text{Total number of households responding to Q4}} ~ \times ~ 100 $$

4a. Percent of households with a household member/s who **often** have had to eat some foods they really didn't want to eat due to a lack of resources to obtain other types of food

$$ \frac{\text{Number of households with response = 3 to Q4a}}{\text{Total number of households responding to Q4}} ~ \times ~ 100 $$

5. Percent of households with a household member/s who have had to eat a smaller meal than they felt they needed because there was not enough food 

$$ \frac{\text{Number of households with response = 1 to Q5}}{\text{Total number of households responding to Q5}} ~ \times ~ 100 $$

5a. Percent of households with a household member/s who **often** have had to eat a smaller meal than they felt they needed because there was not enough food

$$ \frac{\text{Number of households with response = 3 to Q5a}}{\text{Total number of households responding to Q5}} ~ \times ~ 100 $$

6. Percent of households with a household member/s who have had to eat fewer meals in a day because there was not enough food 

$$ \frac{\text{Number of households with response = 1 to Q6}}{\text{Total number of households responding to Q6}} ~ \times ~ 100 $$

6a. Percent of households with a household member/s who **often** have had to eat fewer meals in a day because there was not enough food 

$$ \frac{\text{Number of households with response = 3 to Q6a}}{\text{Total number of households responding to Q6}} ~ \times ~ 100 $$

7. Percent of households in which there was ever no food to eat of any kind because of lack of resources to get food

$$ \frac{\text{Number of households with response = 1 to Q7}}{\text{Total number of households responding to Q7}} ~ \times ~ 100 $$

7a. Percent of households in which there was **often** ever no food to eat of any kind because of lack of resources to get food

$$ \frac{\text{Number of households with response = 3 to Q7a}}{\text{Total number of households responding to Q7}} ~ \times ~ 100 $$

8. Percent of households with a household member/s who had gone to sleep at night hungry because there was not enough food

$$ \frac{\text{Number of households with response = 1 to Q8}}{\text{Total number of households responding to Q8}} ~ \times ~ 100 $$

8a. Percent of households with a household member/s who **often** had gone to sleep at night hungry because there was not enough food

$$ \frac{\text{Number of households with response = 3 to Q8a}}{\text{Total number of households responding to Q8}} ~ \times ~ 100 $$

9. Percent of households with a household member/s who had gone a whole day and night without eating anything because there was not enough food

$$ \frac{\text{Number of households with response = 1 to Q9}}{\text{Total number of households responding to Q9}} ~ \times ~ 100 $$

9a. Percent of households with a household member/s who **often** had gone a whole day and night without eating anything because there was not enough food

$$ \frac{\text{Number of households with response = 3 to Q9a}}{\text{Total number of households responding to Q9}} ~ \times ~ 100 $$

### Household Food Insecurity Access-related Domains

The concurrence questions can be grouped into 3 domains to which they relate to with regard to food insecurity that have been found to be common across cultures. These domains are:

* Anxiety and uncertainty about the household food supply

* Insufficient Quality (includes variety and preferences of the type of food)

* Insufficient food intake and its physical consequences

This indicator set on **domains** consists of responses to the individual **occurence questions** referring to each of the domains. The indicators in this set provide specific, disaggregated information about the behaviours and perceptions of the surveyed households as they pertain to the domains. The indicators present the percent of households that responded affirmatively to each question within a domain, regardless of the frequency of the experience. Thus they measure the percent of households experiencing the condition within a domain at any level of severity.

1. Percent of households with anxiety and uncertainty about the household food supply

$$ \frac{\text{Number of households with response = 1 to Q1}}{\text{Total number of households responding to Q1}} ~ \times ~ 100 $$

2. Percent of households with insufficient good quality

$$ \frac{\text{Number of households with response = 1 to Q2 OR 1 to Q3 OR 1 to Q4}}{\text{Total number of households responding to Q2 OR Q3 OR Q4}} ~ \times ~ 100 $$

3. Percent of households with insufficient food intake

$$ \frac{\text{Number of households with response = 1 to Q5 OR 1 to Q6 OR 1 to Q7 OR 1 to Q8 OR 1 to Q9}}{\text{Total number of households responding to Q5 OR Q6 OR Q7 OR Q8 OR Q9}} ~ \times ~ 100 $$

### Household Food Insecurity Access Scale Score

The HFIAS score is a continuous measure of the degree of food insecurity (access) in the household in the past four weeks (30 days). 

Following are the steps in calculating the HFIAS score.

1. Code the **frequency-of-occurrence** as 0 for all cases where the answer to the corresponding occurrence question was **“no”** (i.e., if **Q1=0** then **Q1a=0**, if **Q2=0** then **Q2a=0**, etc.). 

2. Calculate a HFIAS score variable is calculated for each household by summing the codes for each **frequency-of-occurrence question**. The maximum score for a household is 27 (the household response to all nine frequency-of-occurrence questions was “often”, coded with response code of 3); the minimum score is 0 (the household responded “no” to all occurrence questions, frequency-of-occurrence questions were skipped by the interviewer, and subsequently coded as 0 by the data analyst.) The higher the score, the more food insecurity (access) the household experienced. The lower the score, the less food insecurity (access) a household experienced.

$$ \text{HFIAS Score} ~ = ~ Q1a ~ + ~ Q2a ~ + ~ Q3a ~ + ~ Q4a ~ + ~ Q5a ~ + ~ Q6a ~ + ~ Q7a ~ + ~ Q8a ~ + ~ Q9a $$

3. Next, the average Household Food Insecurity Access Scale Score, is calculated using the household scores calculated above.

$$ \text{Average HFIAS score} ~ = ~ \frac{\sum{\text{HFIAS scores in the sample}}}{\text{Number of households sampled}} $$

### Household Food Insecurity Access Prevalence

The final indicator is a categorical indicator of Food Insecurity Status. The Household Food Insecurity Access Prevalence (HFIAP) Status indicator can be used to report household food insecurity (access) prevalence and make geographic targeting decisions.

Because the average HFIAS score is a continuous variable, it is more sensitive to capturing smaller increments of changes over time than the HFIAP indicator. Therefore, the HFIAP indicator should be reported in addition to, rather than instead of, the average HFIAS Score for program monitoring and evaluation.

The HFIAP indicator categorizes households into four levels of household food insecurity (access): **food secure**, and **mildly**, **moderately** and **severely** food insecure. Households are categorized as increasingly food insecure as they respond affirmatively to more severe conditions and/or experience those conditions more frequently.

Following are the steps in calculating the HFIAP indicator.

1. The data analyst should have coded **frequency-of-occurrence** as 0 for all cases where the answer to the corresponding occurrence question was **“no”** (i.e., if **Q1=0** then **Q1a=0**, if **Q2=0** then **Q2a=0**, etc.)

2. Calculate a HFIA category variable for each household by assigning a code for the food insecurity (access) category in which it falls. The four food security categories should be created sequentially, in the same order as shown below, to ensure that households are classified according to their most severe response.

**Category 1: Food secure**

$$ \text{HFIA category 1 if } [(Q1a = 0 ~ or ~ Q1a = 1) ~ and ~ Q2 = 0 ~ and ~ Q3 = 0 ~ and ~ Q4 = 0 ~ and ~ Q5 = 0 ~ and ~ Q6 = 0 ~ and ~ Q7 = 0 ~ and ~ Q8 = 0 ~ and ~ Q9 = 0] $$


**Category 2: Mildly food insecure access**

$$ \text{HFIA category 2 if } [(Q1a = 2 ~ or ~ Q1a = 3 ~ or ~ Q2a = 1 ~ or ~ Q2a = 2 ~ or ~ Q2a = 3 ~ or ~ Q3a = 1 ~ or ~ Q4a = 1) ~ and ~ Q5 = 0 ~ and ~ Q6 = 0 ~ and ~ Q7 = 0 ~ and ~ Q8 = 0 ~ and ~ Q9 = 0] $$

**Category 3: Moderately food insecure access**

$$ \text{HFIA category 3 if } [(Q3a = 2 ~ or ~ Q3a = 3 ~ or ~ Q4a = 2 ~ or ~ Q4a = 3 ~ or ~ Q5a = 1 ~ or ~ Q5a = 2 ~ or ~ Q6a = 1 ~ or ~ Q6a = 2) ~ and ~ Q7 = 0 ~ and ~ Q8 = 0 ~ and ~ Q9 = 0] $$


**Category 4: Severely food insecure access**

$$ \text{HFIA category 4 if } [Q5a = 3 ~ or ~ Q6a = 3 ~ or ~ Q7a = 1 ~ or ~ Q7a = 2 ~ or ~ Q7a = 3 ~ or ~ Q8a = 1 ~ or ~ Q8a = 2 ~ or ~ Q8a = 3 ~ or ~ Q9a = 1 ~ or ~ Q9a = 2 ~ or ~ Q9a = 3] $$


3. Next, the prevalence of different levels of household food insecurity (access) is calculated.

* Percentage of households that are **food secure**

$$ \% ~ \text{households that are food secure} ~ = ~\frac{\text{Number of households with HFIA category = 1}}{\text{Total number of households with a HFIA category}} $$

* Percentage of households that are **mildly food insecure**

$$ \% ~ \text{households that are mildly food insecure} ~ = ~\frac{\text{Number of households with HFIA category = 2}}{\text{Total number of households with a HFIA category}} $$

* Percentage of households that are **moderately food insecure**

$$ \% ~ \text{households that are moderately food insecure} ~ = ~\frac{\text{Number of households with HFIA category = 3}}{\text{Total number of households with a HFIA category}} $$

* Percentage of households that are **severely food insecure**

$$ \% ~ \text{households that are severely food insecure} ~ = ~\frac{\text{Number of households with HFIA category = 4}}{\text{Total number of households with a HFIA category}} $$